version: '3.8'

services: 
  api-service:
    build: ./tridex-api/
    volumes: 
      - ./tridex-api/:/usr/src/app/
    ports: 
      - 8400:8400
    environment: 
      PORT: 8400
      FLASK_DEBUG: 1
    depends:
      postgres